#!/bin/bash
format_date() {
    date "+%Y%m%d%H%M%S"
}

fleet () {
    dir="${HOME}/github/ageofneil/zet/fleeting/$(format_date)"
    mkdir -p "$dir"
    chmod 777 "$dir"
    touch "$dir/README.md"
    #cat "${HOME}/github/ageofneil/zet/reference/template.md" > "$dir/README.md"
    cd $dir
    vim "README.md"
    line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
    echo "Adding: $line"
    git add -A "$dir"
    git commit -m "$line"
    git push
}

case "$1" in
    add) add;;
    fleet) fleet;;
    p) p;;
    rlist) rlist;;
    *) echo Unsupported Prompt. ;;
esac
